--[[
Fax Core, made by FAXES
Do not edit this file. Please edit the config.lua instead
]]
-- Checks for Ace perms
RegisterServerEvent("Fax:CheckWhite")
AddEventHandler("Fax:CheckWhite", function()
    local src = source
    for a = 1, #AceRanks do
        if IsPlayerAceAllowed(src, AceRanks[a]["rank"]) then
            TriggerClientEvent("Fax:RestrictedHandler", src, AceRanks[a]["rank"])
            TriggerClientEvent("chatMessage", src, "Fax-Core", {255, 0, 0}, "Permissions Checked. You are a : " .. AceRanks[a]["label"])
            return
        end
    end
    TriggerClientEvent("Fax:RestrictedHandler", src, AceRanks[#AceRanks]["rank"])
    TriggerClientEvent("chatMessage", src, "Fax-Core", {255, 0, 0}, "Permissions Checked. You are a : " .. AceRanks[#AceRanks]["label"])
end)

-- Version checker
PerformHttpRequest("http://faxes.zone/files/fax-core/version.txt", function(err, serverVersion, headers)
    local version = "v1.1.0"
    if string.find(serverVersion, version) == nil then
        Wait(120)
        print("\n")
        print("---------------------- Fax-Core ----------------------")
        print("---- ALERT : Your version of Fax-Core is outdated ----")
        print("--- Please update your version as soon as possible ---")
        print("------ http://faxes.zone/scripts/fax-core.html -------")
        print("------------------------------------------------------")
        print("\n")
    else
        Wait(120)
        print("\n")
        print("---------------------- Fax-Core ----------------------")
        print("--------- Fax Core is on the latest version ----------")
        print("------------------------------------------------------")
        print("\n")
    end
end)

Citizen.CreateThread(function ()
check = (GetConvar("Fax-Core", "false") == "true")
    if not check then
        Wait(140)
        print("\n")
        print("---------------------- Fax-Core ----------------------")
        print("------ ALERT: Permissions are not set correctly ------")
        print("--- Please read the Wiki on setting up permissions ---")
        print("------ http://faxes.zone/scripts/fax-core.html -------")
        print("------------------------------------------------------")
        print("\n")
    end
end)