--[[
Fax Core, made by FAXES
Change blacklisted cars in config.lua, Do not edit this file unless you know what your doing.
]]

-- Checks for perms when joining server
AddEventHandler('onClientMapStart', function()
	TriggerServerEvent('Fax:CheckWhite')
end)

-- Teams
plteam = "Team-Guest"

RegisterNetEvent('FaxCore:TeamYes')
AddEventHandler('FaxCore:TeamYes', function()
	plteam = "Team-Admin"
	ShowInfo('~y~Permission System ~n~~w~Your Team is now: Team-Admin')
end)

-- Sets Rank Table, Don't edit
authLvlRank = 
{
	["Guest"] = 0,
	["M1"] = 1,
	["M2"] = 2,
	["M3"] = 3,
	["Admin"] = 4,
	["Sadmin"] = 5,
	["Owner"] = 6,
}

---- Triggering Perms ----
Citizen.CreateThread(function()
	while true do

		local ped = PlayerPedId()
		if DoesEntityExist(ped) and not IsEntityDead(ped) then
			ManageRestrictVehicles()
			ManageRestrictWeaps()
			ManageRestrictPeds()
		end
		Citizen.Wait(500)
	end
end)

RegisterNetEvent("setPlayerGroup")
AddEventHandler("setPlayerGroup", function(group)
	curAuthLvlRank = authLvlRank[group]
end)

RegisterNetEvent("sendNotification")
AddEventHandler("sendNotification", function(string)
	ShowInfo(string)
end)

---- Functions ----
-- Notification
function ShowInfo(text)
	SetNotificationTextEntry("STRING")
	AddTextComponentSubstringPlayerName(text)
	DrawNotification(false, false)
end