--[[
Fax Core, made by FAXES
Change blacklisted peds in config.lua, Do not edit this file unless you know what your doing.
]]
function ManageRestrictPeds()
	local ped_l = PlayerPedId()
	local playerModel = GetEntityModel(ped_l)	

    if curAuthLvlRank < authLvlRank["Admin"] and plteam ~= "Team-Admin" then
        for i = 1, #restrictedPedsStaff do
			local restrictedModel = GetHashKey(restrictedPedsStaff[i])
			if playerModel == restrictedModel then
				RequestModel(newModel)
				while not HasModelLoaded(newModel) do
					Citizen.Wait(0)
				end
				SetPlayerModel(PlayerId(), newModel)
				SetModelAsNoLongerNeeded(newModel)
				ShowInfo("~r~Restricted Ped Model.")
				print("(WARNING) Attempted to spawn restricted staff player model.")
            end
        end
	end
	
    if curAuthLvlRank < authLvlRank["Owner"] then
		for i = 1, #restrictedPedsAll do
			local restrictedModel = GetHashKey(restrictedPedsAll[i])
			if playerModel == restrictedModel then
				RequestModel(newModel)
				while not HasModelLoaded(newModel) do
					Citizen.Wait(0)
				end
				SetPlayerModel(PlayerId(), newModel)
				SetModelAsNoLongerNeeded(newModel)
				ShowInfo("~r~Restricted Ped Model.")
				print("(WARNING) Attempted to spawn restricted player model.")
			end
		end
    end
    
	if curAuthLvlRank < authLvlRank["M3"] then
		for i = 1, #restrictedPedsM3 do
			local restrictedModel = GetHashKey(restrictedPedsM3[i])
			if playerModel == restrictedModel then
				RequestModel(newModel)
				while not HasModelLoaded(newModel) do
					Citizen.Wait(0)
				end
				SetPlayerModel(PlayerId(), newModel)
				SetModelAsNoLongerNeeded(newModel)
				ShowInfo("~r~Restricted Ped Model.")
				print("(WARNING) Attempted to spawn restricted player model.")
			end
		end
	end

	if curAuthLvlRank < authLvlRank["M2"] then
		for i = 1, #restrictedPedsM2 do
			local restrictedModel = GetHashKey(restrictedPedsM2[i])
			if playerModel == restrictedModel then
				RequestModel(newModel)
				while not HasModelLoaded(newModel) do
					Citizen.Wait(0)
				end
				SetPlayerModel(PlayerId(), newModel)
				SetModelAsNoLongerNeeded(newModel)
				ShowInfo("~r~Restricted Ped Model.")
				print("(WARNING) Attempted to spawn restricted player model.")
			end
		end
	end
	
	if curAuthLvlRank < authLvlRank["M1"] then
		for i = 1, #restrictedPedsM1 do
			local restrictedModel = GetHashKey(restrictedPedsM1[i])
			if playerModel == restrictedModel then
				RequestModel(newModel)
				while not HasModelLoaded(newModel) do
					Citizen.Wait(0)
				end
				SetPlayerModel(PlayerId(), newModel)
				SetModelAsNoLongerNeeded(newModel)
				ShowInfo("~r~Restricted Ped Model.")
				print("(WARNING) Attempted to spawn restricted player model.")
			end
		end
	end
end