--[[
	GENERAL CONFIGURATION 
]]
-- Do you have the Whitelist Extension? (Set to "true" or "false").
FaxcWhiteL = true

--[[
Fax Core, made by FAXES
Do not edit this file. Please edit the config.lua instead
]]
-- Checks for Ace perms
RegisterServerEvent("Fax:CheckWhite")
AddEventHandler('Fax:CheckWhite', function()

    if IsPlayerAceAllowed(source, "owner") then
        -- Fax Core
        TriggerClientEvent("Fax:owner", source)
        TriggerClientEvent("Fax:ownerMessage", source)

    elseif IsPlayerAceAllowed(source, "snradmin") then
        -- Fax Core
        TriggerClientEvent("Fax:sadmin", source)
        TriggerClientEvent("Fax:sadminMessage", source)
        -- Fax Core Whitelist

    elseif IsPlayerAceAllowed(source, "fadmin") then
        -- Fax Core
        TriggerClientEvent("Fax:fadmin", source)
        TriggerClientEvent("Fax:fadminMessage", source)
        -- Fax Core Whitelist

    elseif IsPlayerAceAllowed(source, "member3") then
        -- Fax Core
        TriggerClientEvent("Fax:member3", source)
        TriggerClientEvent("Fax:m3Message", source)
        -- Fax Core Whitelist

    elseif IsPlayerAceAllowed(source, "member2") then
        -- Fax Core
        TriggerClientEvent("Fax:member2", source)
        TriggerClientEvent("Fax:m2Message", source)
        -- Fax Core Whitelist

    elseif IsPlayerAceAllowed(source, "member1") then
        -- Fax Core
        TriggerClientEvent("Fax:member1", source)
        TriggerClientEvent("Fax:m1Message", source)
        -- Fax Core Whitelist

    else
        -- Fax Core
        TriggerClientEvent("Fax:guest", source)
        TriggerClientEvent("Fax:guestMessage", source)
        -- Fax Core Whitelist

    end
end)

-- ODA Command
RegisterCommand("oda", function(source, args, rawCommand)
    if IsPlayerAceAllowed(source, "owner") then
        TriggerClientEvent("FaxCore:TeamYes", source)
    -- Check for senior admin perms
    elseif IsPlayerAceAllowed(source, "snradmin") then
        TriggerClientEvent("FaxCore:TeamYes", source)
    -- Check for admin perms
    elseif IsPlayerAceAllowed(source, "fadmin") then
        TriggerClientEvent("FaxCore:TeamYes", source)
	else
		print('FaxCore : Access Denied after /ODA was used.')
	end
end)

-- Version checker
PerformHttpRequest("http://faxes.zone/files/fax-core/version.txt", function(err, serverVersion, headers)
    local version = "v2.1.0"
    if string.find(serverVersion, version) == nil then
        Wait(120)
        print("\n")
        print("---------------------- Fax-Core ----------------------")
        print("---- ALERT : Your version of Fax-Core is outdated ----")
        print("--- Please update your version as soon as possible ---")
        print("------ http://faxes.zone/scripts/fax-core.html -------")
        print("------------------------------------------------------")
        print("\n")
    else
        Wait(120)
        print("\n")
        print("---------------------- Fax-Core ----------------------")
        print("--------- Fax Core is on the latest version ----------")
        print("------------------------------------------------------")
    end
end)

Citizen.CreateThread(function ()
check = (GetConvar("Fax-Core", "false") == "true")
    if not check then
        Wait(140)
        print("\n")
        print("---------------------- Fax-Core ----------------------")
        print("------ ALERT: Permissions are not set correctly ------")
        print("--- Please read the Wiki on setting up permissions ---")
        print("------ http://faxes.zone/scripts/fax-core.html -------")
        print("------------------------------------------------------")
        print("\n")
    end
end)