--[[
Fax Core, made by FAXES
--- Change blacklisted cars in config.lua, Do not edit this file at all! ---
]]
AddEventHandler('onClientMapStart', function()
	TriggerServerEvent('Fax:CheckWhite')
	TriggerServerEvent('Fax:CheckWhiteMessage')
end)

-- Owner Vehicle Permission Check
RegisterNetEvent('Fax:owner')
AddEventHandler('Fax:owner', function() 
	while true do
		playerPed = GetPlayerPed(-1)
		if playerPed then
			checkCarowner(GetVehiclePedIsIn(playerPed, false))
			x, y, z = table.unpack(GetEntityCoords(playerPed, true))
			for _, blacklistedCar in pairs(ownercarblacklist) do
				checkCarowner(GetClosestVehicle(x, y, z, 100.0, GetHashKey(blacklistedCar), 70))
			end
		end
		nothing, weapon = GetCurrentPedWeapon(playerPed, true)
		if isWeaponBlacklistedowner(weapon) then
			RemoveWeaponFromPed(playerPed, weapon)
			notifygun()
		end
		playerModel = GetEntityModel(playerPed)
		RequestModel(GetHashKey("a_m_y_skater_01"))
		if isPedBlacklistedowner(playerModel) then
			SetPlayerModel(PlayerId(), GetHashKey(defaultpedmodel))
			notifyped()
		end
		Citizen.Wait(250)
	end
end)

-- Senior Admin Vehicle Permission Check
RegisterNetEvent('Fax:sadmin')
AddEventHandler('Fax:sadmin', function() 
	while true do
		playerPed = GetPlayerPed(-1)
		if playerPed then
			checkCarsadmin(GetVehiclePedIsIn(playerPed, false))
			x, y, z = table.unpack(GetEntityCoords(playerPed, true))
			for _, blacklistedCar in pairs(sadmincarblacklist) do
				checkCarsadmin(GetClosestVehicle(x, y, z, 100.0, GetHashKey(blacklistedCar), 70))
			end
		end
		nothing, weapon = GetCurrentPedWeapon(playerPed, true)
		if isWeaponBlacklistedsadmin(weapon) then
			RemoveWeaponFromPed(playerPed, weapon)
			notifygun()
		end
		playerModel = GetEntityModel(playerPed)
		RequestModel(GetHashKey("a_m_y_skater_01"))
		if isPedBlacklistedsadmin(playerModel) then
			SetPlayerModel(PlayerId(), GetHashKey(defaultpedmodel))
			notifyped()
		end
		Citizen.Wait(250)
	end
end)

-- Admin Vehicle Permission Check
RegisterNetEvent('Fax:fadmin')
AddEventHandler('Fax:fadmin', function() 
	while true do
		playerPed = GetPlayerPed(-1)
		if playerPed then
			checkCaradmin(GetVehiclePedIsIn(playerPed, false))
			x, y, z = table.unpack(GetEntityCoords(playerPed, true))
			for _, blacklistedCar in pairs(admincarblacklist) do
				checkCaradmin(GetClosestVehicle(x, y, z, 100.0, GetHashKey(blacklistedCar), 70))
			end
		end
		nothing, weapon = GetCurrentPedWeapon(playerPed, true)
		if isWeaponBlacklistedadmin(weapon) then
			RemoveWeaponFromPed(playerPed, weapon)
			notifygun()
		end
		playerModel = GetEntityModel(playerPed)
		RequestModel(GetHashKey("a_m_y_skater_01"))
		if isPedBlacklistedadmin(playerModel) then
			SetPlayerModel(PlayerId(), GetHashKey(defaultpedmodel))
			notifyped()
		end
		Citizen.Wait(250)
	end
end)

-- Member 3 Vehicle Permission Check
RegisterNetEvent('Fax:member3')
AddEventHandler('Fax:member3', function() 
	while true do
		playerPed = GetPlayerPed(-1)
		if playerPed then
			checkCarm3(GetVehiclePedIsIn(playerPed, false))
			x, y, z = table.unpack(GetEntityCoords(playerPed, true))
			for _, blacklistedCar in pairs(m3carblacklist) do
				checkCarm3(GetClosestVehicle(x, y, z, 100.0, GetHashKey(blacklistedCar), 70))
			end
		end
		nothing, weapon = GetCurrentPedWeapon(playerPed, true)
		if isWeaponBlacklistedm3(weapon) then
			RemoveWeaponFromPed(playerPed, weapon)
			notifygun()
		end
		playerModel = GetEntityModel(playerPed)
		RequestModel(GetHashKey("a_m_y_skater_01"))
		if isPedBlacklistedm3(playerModel) then
			SetPlayerModel(PlayerId(), GetHashKey(defaultpedmodel))
			notifyped()
		end
		Citizen.Wait(250)
	end
end)

-- Member 2 Vehicle Permission Check
RegisterNetEvent('Fax:member2')
AddEventHandler('Fax:member2', function() 
	while true do
		playerPed = GetPlayerPed(-1)
		if playerPed then
			checkCarm2(GetVehiclePedIsIn(playerPed, false))
			x, y, z = table.unpack(GetEntityCoords(playerPed, true))
			for _, blacklistedCar in pairs(m2carblacklist) do
				checkCarm2(GetClosestVehicle(x, y, z, 100.0, GetHashKey(blacklistedCar), 70))
			end
		end
		nothing, weapon = GetCurrentPedWeapon(playerPed, true)
		if isWeaponBlacklistedm2(weapon) then
			RemoveWeaponFromPed(playerPed, weapon)
			notifygun()
		end
		playerModel = GetEntityModel(playerPed)
		RequestModel(GetHashKey("a_m_y_skater_01"))
		if isPedBlacklistedm2(playerModel) then
			SetPlayerModel(PlayerId(), GetHashKey(defaultpedmodel))
			notifyped()
		end
		Citizen.Wait(250)
	end
end)

-- Member 2 Vehicle Permission Check
RegisterNetEvent('Fax:member1')
AddEventHandler('Fax:member1', function() 
	while true do
		playerPed = GetPlayerPed(-1)
		if playerPed then
			checkCarm1(GetVehiclePedIsIn(playerPed, false))
			x, y, z = table.unpack(GetEntityCoords(playerPed, true))
			for _, blacklistedCar in pairs(m1carblacklist) do
				checkCarm1(GetClosestVehicle(x, y, z, 100.0, GetHashKey(blacklistedCar), 70))
			end
		end
		nothing, weapon = GetCurrentPedWeapon(playerPed, true)
		if isWeaponBlacklistedm1(weapon) then
			RemoveWeaponFromPed(playerPed, weapon)
			notifygun()
		end
		playerModel = GetEntityModel(playerPed)
		RequestModel(GetHashKey("a_m_y_skater_01"))
		if isPedBlacklistedm1(playerModel) then
			SetPlayerModel(PlayerId(), GetHashKey(defaultpedmodel))
			notifyped()
		end
		Citizen.Wait(250)
	end
end)

-- Guest Vehicle Permission Check
RegisterNetEvent('Fax:guest')
AddEventHandler('Fax:guest', function() 
	while true do
		playerPed = GetPlayerPed(-1)
		if playerPed then
			checkCarguest(GetVehiclePedIsIn(playerPed, false))
			x, y, z = table.unpack(GetEntityCoords(playerPed, true))
			for _, blacklistedCar in pairs(guestcarblacklist) do
				checkCarguest(GetClosestVehicle(x, y, z, 100.0, GetHashKey(blacklistedCar), 70))
			end
		end
		nothing, weapon = GetCurrentPedWeapon(playerPed, true)
		if isWeaponBlacklistedguest(weapon) then
			RemoveWeaponFromPed(playerPed, weapon)
			notifygun()
		end
		playerModel = GetEntityModel(playerPed)
		RequestModel(GetHashKey("a_m_y_skater_01"))
		if isPedBlacklistedguest(playerModel) then
			SetPlayerModel(PlayerId(), GetHashKey(defaultpedmodel))
			notifyped()
		end
		Citizen.Wait(250)
	end
end)

