--[[
Fax Core, made by FAXES
Do not edit this file. Please edit the config.lua instead
]]
--- This file sends the permissions checked messages to the client
-- Sends owner checked message
RegisterNetEvent('Fax:ownerMessage')
AddEventHandler('Fax:ownerMessage', function()
	TriggerEvent("chatMessage", "SYSTEM", {255, 0, 0}, "Your permission level is: Owner")
end)
-- Sends senior admin checked message
RegisterNetEvent('Fax:sadminMessage')
AddEventHandler('Fax:sadminMessage', function()
	TriggerEvent("chatMessage", "SYSTEM", {255, 0, 0}, "Your permission level is: Senior Admin")
end)
-- Sends admin checked message
RegisterNetEvent('Fax:fadminMessage')
AddEventHandler('Fax:fadminMessage', function()
	TriggerEvent("chatMessage", "SYSTEM", {255, 0, 0}, "Your permission level is: Admin")
end)
-- Sends member 3 checked message
RegisterNetEvent('Fax:m3Message')
AddEventHandler('Fax:m3Message', function()
	TriggerEvent("chatMessage", "SYSTEM", {255, 0, 0}, "Your permission level is: Member level 3")
end)
-- Sends member 2 checked message
RegisterNetEvent('Fax:m2Message')
AddEventHandler('Fax:m2Message', function()
	TriggerEvent("chatMessage", "SYSTEM", {255, 0, 0}, "Your permission level is: Member level 2")
end)
-- Sends member 1 checked message
RegisterNetEvent('Fax:m1Message')
AddEventHandler('Fax:m1Message', function()
	TriggerEvent("chatMessage", "SYSTEM", {255, 0, 0}, "Your permission level is: Member level 1")
end)
-- Sends guest checked message
RegisterNetEvent('Fax:guestMessage')
AddEventHandler('Fax:guestMessage', function()
	TriggerEvent("chatMessage", "SYSTEM", {255, 0, 0}, "Your permission level is: Guest")
end)

--- General No Perms Message
RegisterNetEvent('Fax-Core:NoPerms')
AddEventHandler('Fax-Core:NoPerms', function()
    TriggerEvent("chatMessage", "SYSTEM", {255, 0, 0}, "Insufficient permissions")
end)
