--[[
Fax Core, made by FAXES
--- Change blacklisted cars in config.lua, Do not edit this file at all! ---
]]
Citizen.CreateThread(function()
	TriggerServerEvent("Fax:CheckWhite")
end)

RegisterNetEvent("Fax:RestrictedHandler")
AddEventHandler("Fax:RestrictedHandler", function(rank)
	while true do
		local ped = GetPlayerPed(-1)

		if ped then
			-- Vehicle
			local vehicle = GetVehiclePedIsIn(ped, false)
			if vehicle ~= 0 then
				if CheckVehicleBlacklist(vehicle, rank) then
					_DeleteEntity(vehicle)
					Notification(Messages["vehicle"])
				end
			end

			-- Weapons
			local hasWeapon, weapon = GetCurrentPedWeapon(ped, true)
			if hasWeapon then
				if CheckWeaponBlacklist(weapon, rank) then
					RemoveWeaponFromPed(ped, weapon)
					Notification(Messages["weapon"])
				end
			end

			-- Peds
			if CheckPedBlacklist(ped, rank) then
				local model = PedBlacklist["defaultpedmodel"]
				RequestModel(model)
				while not HasModelLoaded(model) do
					Citizen.Wait(100)
				end
				SetPlayerModel(PlayerId(), model)
				Notification(Messages["ped"])
			end
		end
		Citizen.Wait(100)
	end
end)