--[[
Fax Core, made by FAXES
Do not edit this file. Please edit the config.lua instead
]]

function CheckVehicleBlacklist(model, rank)
	local model = GetEntityModel(model)
	for a = 1, #VehicleBlacklist[rank] do
		if model == GetHashKey(VehicleBlacklist[rank][a]) then
			return true
		end
	end
	return false
end

function CheckWeaponBlacklist(model, rank)
	for a = 1, #WeaponBlacklist[rank] do
		if model == GetHashKey(WeaponBlacklist[rank][a]) then
			return true
		end
	end
	return false
end

function CheckPedBlacklist(model, rank)
	local model = GetEntityModel(model)
	for a = 1, #PedBlacklist["ranks"][rank] do
		if model == GetHashKey(PedBlacklist["ranks"][rank][a]) then
			return true
		end
	end
	return false
end

-- Global Functions
function _DeleteEntity(entity)
	Citizen.InvokeNative(0xAE3CBE5BF394C9C9, Citizen.PointerValueIntInitialized(entity))
end

function Notification(message)
	SetNotificationTextEntry("STRING")
	AddTextComponentSubstringPlayerName(message)
	DrawNotification(true, true)
end